CREATE TABLE IF NOT EXISTS EMPLOYEE(
  EMPLOYEE_ID TEXT,
  EMPLOYEE_NAME TEXT,
  DEPARTMENT TEXT,
  SALARY REAL
);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT, SALARY) VALUES
  ('1', 'Natt Byron', 'Finance', 18000),
  ('2', 'James Lyon', 'Marketing', 20000),
  ('3', 'Yori Lite', 'Sales', 16000),
  ('4', 'Paul Hen', 'Sales', 22200),
  ('5', 'Cora Lane', 'Marketing', 21000);
SELECT SUM(SALARY) AS Total_Salary
FROM EMPLOYEE;
SELECT AVG(SALARY) AS Average_SALARY
FROM EMPLOYEE;
SELECT COUNT(DEPARTMENT) AS DEPARTMENT_Count
FROM EMPLOYEE;
SELECT MIN(SALARY) AS Smallest_Salary
FROM EMPLOYEE;
SELECT MAX(SALARY) AS Largest_Salary
FROM EMPLOYEE;